CREATE TABLE `op_direct_master_base` (
  `op_direct_master_base_id` int(11) NOT NULL AUTO_INCREMENT,
  `supply_pttep_input` decimal(19,2) NOT NULL DEFAULT '0.00',
  `supply_got_other_input` decimal(19,2) NOT NULL DEFAULT '0.00',
  `supply_spot_lng_input` decimal(19,2) NOT NULL DEFAULT '0.00',
  `supply_lng_contract_input` decimal(19,2) NOT NULL DEFAULT '0.00',
  `supply_spot_lng_tp_input` decimal(19,2) NOT NULL DEFAULT '0.00',
  `supply_myanmar_import_input` decimal(19,2) NOT NULL DEFAULT '0.00',
  `supply_got_input` decimal(19,2) NOT NULL DEFAULT '0.00',
  `conversion_pttep` decimal(19,2) NOT NULL DEFAULT '0.00',
  `conversion_pttgsp_c1` decimal(19,2) NOT NULL DEFAULT '0.00',
  `conversion_lng_terminal_c1` decimal(19,2) NOT NULL DEFAULT '0.00',
  `transmission_pttgsp_c2` decimal(19,2) NOT NULL DEFAULT '0.00',
  `transmission_pttgsp_lpg` decimal(19,2) NOT NULL DEFAULT '0.00',
  `transmission_refinery` decimal(19,2) NOT NULL DEFAULT '0.00',
  `transmission_superheader` decimal(19,2) NOT NULL DEFAULT '0.00',
  `transmission_superheader_ngv` decimal(19,2) NOT NULL DEFAULT '0.00',
  `transmission_superheader_indusers` decimal(19,2) NOT NULL DEFAULT '0.00',
  `transmission_superheader_opg` decimal(19,2) NOT NULL DEFAULT '0.00',
  `sales_petchem_c2` decimal(19,2) NOT NULL DEFAULT '0.00',
  `sales_petchem_c3` decimal(19,2) NOT NULL DEFAULT '0.00',
  `sales_petchem_lpg` decimal(19,2) NOT NULL DEFAULT '0.00',
  `sales_petchem_ngl` decimal(19,2) NOT NULL DEFAULT '0.00',
  `sales_lpg_domestic` decimal(19,2) NOT NULL DEFAULT '0.00',
  `sales_opg` decimal(19,2) NOT NULL DEFAULT '0.00',
  `demand_gc_c2` decimal(19,2) NOT NULL DEFAULT '0.00',
  `demand_gc_c3` decimal(19,2) NOT NULL DEFAULT '0.00',
  `demand_gc_lpg` decimal(19,2) NOT NULL DEFAULT '0.00',
  `demand_gc_ngl` decimal(19,2) NOT NULL DEFAULT '0.00',
  `demand_lpg_or` decimal(19,2) NOT NULL DEFAULT '0.00',
  `demand_lpg_other` decimal(19,2) NOT NULL DEFAULT '0.00',
  `demand_c1_gpsc` decimal(19,2) NOT NULL DEFAULT '0.00',
  `demand_other` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_summary_ptt` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_summary_thailand` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_pttep` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_gsm` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_gsp` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_gtm` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_pttgc` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_pttor` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_gpsc` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_tbu` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_total_ptt` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_moe` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_mof` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_power_consumers` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_total_thailand` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vn_total` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vn_other_feedback` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `revision_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `planning_date` date NOT NULL,
  PRIMARY KEY (`op_direct_master_base_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE `op_direct_master_senario_1` (
  `op_direct_master_senario_1_id` int(11) NOT NULL AUTO_INCREMENT,
  `supply_pttep_input` decimal(19,2) NOT NULL DEFAULT '0.00',
  `supply_got_other_input` decimal(19,2) NOT NULL DEFAULT '0.00',
  `supply_spot_lng_input` decimal(19,2) NOT NULL DEFAULT '0.00',
  `supply_lng_contract_input` decimal(19,2) NOT NULL DEFAULT '0.00',
  `supply_spot_lng_tp_input` decimal(19,2) NOT NULL DEFAULT '0.00',
  `supply_myanmar_import_input` decimal(19,2) NOT NULL DEFAULT '0.00',
  `supply_got_input` decimal(19,2) NOT NULL DEFAULT '0.00',
  `conversion_pttep` decimal(19,2) NOT NULL DEFAULT '0.00',
  `conversion_pttgsp_c1` decimal(19,2) NOT NULL DEFAULT '0.00',
  `conversion_lng_terminal_c1` decimal(19,2) NOT NULL DEFAULT '0.00',
  `transmission_pttgsp_c2` decimal(19,2) NOT NULL DEFAULT '0.00',
  `transmission_pttgsp_lpg` decimal(19,2) NOT NULL DEFAULT '0.00',
  `transmission_refinery` decimal(19,2) NOT NULL DEFAULT '0.00',
  `transmission_superheader` decimal(19,2) NOT NULL DEFAULT '0.00',
  `transmission_superheader_ngv` decimal(19,2) NOT NULL DEFAULT '0.00',
  `transmission_superheader_indusers` decimal(19,2) NOT NULL DEFAULT '0.00',
  `transmission_superheader_opg` decimal(19,2) NOT NULL DEFAULT '0.00',
  `sales_petchem_c2` decimal(19,2) NOT NULL DEFAULT '0.00',
  `sales_petchem_c3` decimal(19,2) NOT NULL DEFAULT '0.00',
  `sales_petchem_lpg` decimal(19,2) NOT NULL DEFAULT '0.00',
  `sales_petchem_ngl` decimal(19,2) NOT NULL DEFAULT '0.00',
  `sales_lpg_domestic` decimal(19,2) NOT NULL DEFAULT '0.00',
  `sales_opg` decimal(19,2) NOT NULL DEFAULT '0.00',
  `demand_gc_c2` decimal(19,2) NOT NULL DEFAULT '0.00',
  `demand_gc_c3` decimal(19,2) NOT NULL DEFAULT '0.00',
  `demand_gc_lpg` decimal(19,2) NOT NULL DEFAULT '0.00',
  `demand_gc_ngl` decimal(19,2) NOT NULL DEFAULT '0.00',
  `demand_lpg_or` decimal(19,2) NOT NULL DEFAULT '0.00',
  `demand_lpg_other` decimal(19,2) NOT NULL DEFAULT '0.00',
  `demand_c1_gpsc` decimal(19,2) NOT NULL DEFAULT '0.00',
  `demand_other` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_summary_ptt` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_summary_thailand` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_pttep` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_gsm` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_gsp` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_gtm` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_pttgc` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_pttor` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_gpsc` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_tbu` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_total_ptt` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_moe` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_mof` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_power_consumers` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_total_thailand` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vn_total` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vn_other_feedback` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `revision_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `planning_date` date NOT NULL,
  PRIMARY KEY (`op_direct_master_senario_1_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE `op_direct_master_senario_2` (
  `op_direct_master_senario_2_id` int(11) NOT NULL AUTO_INCREMENT,
  `supply_pttep_input` decimal(19,2) NOT NULL DEFAULT '0.00',
  `supply_got_other_input` decimal(19,2) NOT NULL DEFAULT '0.00',
  `supply_spot_lng_input` decimal(19,2) NOT NULL DEFAULT '0.00',
  `supply_lng_contract_input` decimal(19,2) NOT NULL DEFAULT '0.00',
  `supply_spot_lng_tp_input` decimal(19,2) NOT NULL DEFAULT '0.00',
  `supply_myanmar_import_input` decimal(19,2) NOT NULL DEFAULT '0.00',
  `supply_got_input` decimal(19,2) NOT NULL DEFAULT '0.00',
  `conversion_pttep` decimal(19,2) NOT NULL DEFAULT '0.00',
  `conversion_pttgsp_c1` decimal(19,2) NOT NULL DEFAULT '0.00',
  `conversion_lng_terminal_c1` decimal(19,2) NOT NULL DEFAULT '0.00',
  `transmission_pttgsp_c2` decimal(19,2) NOT NULL DEFAULT '0.00',
  `transmission_pttgsp_lpg` decimal(19,2) NOT NULL DEFAULT '0.00',
  `transmission_refinery` decimal(19,2) NOT NULL DEFAULT '0.00',
  `transmission_superheader` decimal(19,2) NOT NULL DEFAULT '0.00',
  `transmission_superheader_ngv` decimal(19,2) NOT NULL DEFAULT '0.00',
  `transmission_superheader_indusers` decimal(19,2) NOT NULL DEFAULT '0.00',
  `transmission_superheader_opg` decimal(19,2) NOT NULL DEFAULT '0.00',
  `sales_petchem_c2` decimal(19,2) NOT NULL DEFAULT '0.00',
  `sales_petchem_c3` decimal(19,2) NOT NULL DEFAULT '0.00',
  `sales_petchem_lpg` decimal(19,2) NOT NULL DEFAULT '0.00',
  `sales_petchem_ngl` decimal(19,2) NOT NULL DEFAULT '0.00',
  `sales_lpg_domestic` decimal(19,2) NOT NULL DEFAULT '0.00',
  `sales_opg` decimal(19,2) NOT NULL DEFAULT '0.00',
  `demand_gc_c2` decimal(19,2) NOT NULL DEFAULT '0.00',
  `demand_gc_c3` decimal(19,2) NOT NULL DEFAULT '0.00',
  `demand_gc_lpg` decimal(19,2) NOT NULL DEFAULT '0.00',
  `demand_gc_ngl` decimal(19,2) NOT NULL DEFAULT '0.00',
  `demand_lpg_or` decimal(19,2) NOT NULL DEFAULT '0.00',
  `demand_lpg_other` decimal(19,2) NOT NULL DEFAULT '0.00',
  `demand_c1_gpsc` decimal(19,2) NOT NULL DEFAULT '0.00',
  `demand_other` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_summary_ptt` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_summary_thailand` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_pttep` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_gsm` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_gsp` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_gtm` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_pttgc` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_pttor` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_gpsc` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_tbu` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_total_ptt` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_moe` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_mof` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_power_consumers` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vf_total_thailand` decimal(19,2) NOT NULL DEFAULT '0.00',
   `vn_total` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vn_other_feedback` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `revision_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `planning_date` date NOT NULL,
  PRIMARY KEY (`op_direct_master_senario_2_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE `op_direct_master_senario_3` (
  `op_direct_master_senario_3_id` int(11) NOT NULL AUTO_INCREMENT,
  `supply_pttep_input` DECIMAL(19,2 ) NOT NULL default 0,
  `supply_got_other_input` DECIMAL(19,2 ) NOT NULL default 0,
  `supply_spot_lng_input` DECIMAL(19,2 ) NOT NULL default 0,
  `supply_lng_contract_input` DECIMAL(19,2 ) NOT NULL default 0,
  `supply_spot_lng_tp_input` DECIMAL(19,2 ) NOT NULL default 0,
  `supply_myanmar_import_input` DECIMAL(19,2 ) NOT NULL default 0,
  `supply_got_input` DECIMAL(19,2 ) NOT NULL default 0,
  `conversion_pttep` DECIMAL(19,2 ) NOT NULL default 0,
  `conversion_pttgsp_c1` DECIMAL(19,2 ) NOT NULL default 0,
  `conversion_lng_terminal_c1` DECIMAL(19,2 ) NOT NULL default 0,
  `transmission_pttgsp_c2` DECIMAL(19,2 ) NOT NULL default 0,
  `transmission_pttgsp_lpg` DECIMAL(19,2 ) NOT NULL default 0,
  `transmission_refinery` DECIMAL(19,2 ) NOT NULL default 0,
  `transmission_superheader` DECIMAL(19,2 ) NOT NULL default 0,
  `transmission_superheader_ngv` DECIMAL(19,2 ) NOT NULL default 0,
  `transmission_superheader_indusers` DECIMAL(19,2 ) NOT NULL default 0,
  `transmission_superheader_opg` DECIMAL(19,2 ) NOT NULL default 0,
  `sales_petchem_c2` DECIMAL(19,2 ) NOT NULL default 0,
  `sales_petchem_c3` DECIMAL(19,2 ) NOT NULL default 0,
  `sales_petchem_lpg` DECIMAL(19,2 ) NOT NULL default 0,
  `sales_petchem_ngl` DECIMAL(19,2 ) NOT NULL default 0,
  `sales_lpg_domestic` DECIMAL(19,2 ) NOT NULL default 0,
  `sales_opg` DECIMAL(19,2 ) NOT NULL default 0,
  `demand_gc_c2` DECIMAL(19,2 ) NOT NULL default 0,
  `demand_gc_c3` DECIMAL(19,2 ) NOT NULL default 0,
  `demand_gc_lpg` DECIMAL(19,2 ) NOT NULL default 0,
  `demand_gc_ngl` DECIMAL(19,2 ) NOT NULL default 0,
  `demand_lpg_or` DECIMAL(19,2 ) NOT NULL default 0,
  `demand_lpg_other` DECIMAL(19,2 ) NOT NULL default 0,
  `demand_c1_gpsc` DECIMAL(19,2 ) NOT NULL default 0,
  `demand_other` DECIMAL(19,2 ) NOT NULL default 0,
  `vf_summary_ptt` DECIMAL(19,2 ) NOT NULL default 0,
  `vf_summary_thailand` DECIMAL(19,2 ) NOT NULL default 0,
  `vf_pttep` DECIMAL(19,2 ) NOT NULL default 0,
  `vf_gsm` DECIMAL(19,2 ) NOT NULL default 0,
  `vf_gsp` DECIMAL(19,2 ) NOT NULL default 0,
  `vf_gtm` DECIMAL(19,2 ) NOT NULL default 0,
  `vf_pttgc` DECIMAL(19,2 ) NOT NULL default 0,
  `vf_pttor` DECIMAL(19,2 ) NOT NULL default 0,
  `vf_gpsc` DECIMAL(19,2 ) NOT NULL default 0,
  `vf_tbu` DECIMAL(19,2 ) NOT NULL default 0,
  `vf_total_ptt` DECIMAL(19,2 ) NOT NULL default 0,
  `vf_moe` DECIMAL(19,2 ) NOT NULL default 0,
  `vf_mof` DECIMAL(19,2 ) NOT NULL default 0,
  `vf_power_consumers` DECIMAL(19,2 ) NOT NULL default 0,
  `vf_total_thailand` DECIMAL(19,2 ) NOT NULL default 0,
  `revision_name` varchar(255) NOT NULL COLLATE utf8_unicode_ci,
  `vn_total` decimal(19,2) NOT NULL DEFAULT '0.00',
  `vn_other_feedback` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `planning_date` DATE NOT NULL,
  PRIMARY KEY (`op_direct_master_senario_3_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;






